SongScreenerMvc/Models/VSong.cs
#region Header

// -----------------------------------------------------------------------
// SongScreenerMvc-SongScreenerMvc-VSong.cs
// clijiac  201212-28
// -----------------------------------------------------------------------

#endregion

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SongScreenerMvc.Models.Entity;

namespace SongScreenerMvc.Models
{
    public class VSong 
    {
        public System.Guid SongID { get; set; }
        //[Required(ErrorMessage = "必须输入")]
        [DisplayName("歌曲名")]
        public string SongName { get; set; }
        [Required(ErrorMessage = "必须输入")]
        [DisplayName("音色")]
        [Range(0, 10, ErrorMessage = "节奏必须在0到10之间")]
        public int Intonation { get; set; }
        [Required(ErrorMessage = "必须输入")]
        [DisplayName("声调")]
        [Range(0, 10, ErrorMessage = "节奏必须在0到10之间")]
        public int Tone { get; set; }
        [Required(ErrorMessage = "必须输入")]
        [DisplayName("节奏")]
        [Range(0, 10, ErrorMessage = "节奏必须在0到10之间")]
        public int Rhythm { get; set; }
        //[Required(ErrorMessage = "必须输入")]
        [DisplayName("歌曲路径")]
        public string FliePath { get; set; }
        [Required(ErrorMessage = "必须输入")]
        [DisplayName("歌手")]
        public Artist Artist { get; set; }
        //[Required(ErrorMessage = "必须输入")]
        [DisplayName("后缀名")]
        public Extension Extension { get; set; }
        [Required(ErrorMessage = "必须输入")]
        [DisplayName("流派")]
        public Genre Genre { get; set; }
        [Required(ErrorMessage = "必须输入")]
        [DisplayName("语言")]
        public Language Language { get; set; }

        public System.Guid SongArtistID { get; set; }
        public System.Guid SongLanguageID { get; set; }
        public System.Guid SongGenreID { get; set; }
        public System.Guid SongExtensionID { get; set; }
        public VSong(Song song)
        {
            Artist = song.Artist;
            Extension = song.Extension;
            Genre = song.Genre;
            Language = song.Language;
            SongID = song.SongID;
            SongName = song.SongName;
            Intonation = song.SongIntonation;
            Tone = song.SongTone;
            Rhythm = song.SongRhythm;
            FliePath = song.SongPath;
            SongArtistID = song.SongArtistID;
            SongLanguageID = song.SongLanguageID;
            SongGenreID = song.SongGenreID;
            SongExtensionID = song.SongExtensionID;
        }
        public VSong(){}
    }
}

SongScreenerMvc/Controllers/VSongController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SongScreenerMvc.Models;
using SongScreenerMvc.Models.Entity;
using SongScreenerMvc.Utility;

namespace SongScreenerMvc.Controllers
{
    
    public class VSongController : Controller
    {
        private SongScreenerDBEntities db = new SongScreenerDBEntities();

        //
        // GET: /VSong/

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            ViewBag.SongArtistID = new SelectList(db.Artist, "ArtistID", "ArtistName");
            ViewBag.SongExtensionID = new SelectList(db.Extension, "ExtensionID", "ExtensionName");
            ViewBag.SongGenreID = new SelectList(db.Genre, "GenreID", "GenreName");
            ViewBag.SongLanguageID = new SelectList(db.Language, "LanguageID", "LanguageName");
           
            return View();
        }

        //
        // GET: /VSong/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(Guid id)
        {
            Song song = db.Song.Find(id);
           VSong vSong = new VSong(song);
           return View(vSong);
        }

        //
        // GET: /VSong/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.SongArtistID = new SelectList(db.Artist, "ArtistID", "ArtistName");
            ViewBag.SongExtensionID = new SelectList(db.Extension, "ExtensionID", "ExtensionName");
            ViewBag.SongGenreID = new SelectList(db.Genre, "GenreID", "GenreName");
            ViewBag.SongLanguageID = new SelectList(db.Language, "LanguageID", "LanguageName");
            return View();
        }

        //
        // POST: /VSong/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(VSong song)
        {
            try
            {
                var newsong = Newsong(song);
                db.Song.Add(newsong);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.SongArtistID = new SelectList(db.Artist, "ArtistID", "ArtistName");
                ViewBag.SongExtensionID = new SelectList(db.Extension, "ExtensionID", "ExtensionName");
                ViewBag.SongGenreID = new SelectList(db.Genre, "GenreID", "GenreName");
                ViewBag.SongLanguageID = new SelectList(db.Language, "LanguageID", "LanguageName");
                return View();
            }
        }

        [NonAction]
        private Song Newsong(VSong song)
        {
            Song newsong = new Song
                               {
                                   SongName = song.SongName,
                                   Artist = song.Artist,
                                   Extension = db.Extension.FirstOrDefault(p => p.ExtensionID == song.SongExtensionID),
                                   Genre = db.Genre.FirstOrDefault(p => p.GenreID == song.SongGenreID),
                                   Language = db.Language.FirstOrDefault(p => p.LanguageID == song.SongLanguageID),
                                   SongID = song.SongID,
                                   SongIntonation = song.Intonation,
                                   SongTone = song.Tone,
                                   SongRhythm = song.Rhythm,
                                   SongPath = song.FliePath,
                                   SongArtistID = song.SongArtistID,
                                   SongLanguageID = song.SongLanguageID,
                                   SongGenreID = song.SongGenreID,
                                   SongExtensionID = song.SongExtensionID
                               };
            return newsong;
        }

        //
        // GET: /VSong/Edit/5

        public ActionResult Edit(Guid id)
        {
            Song song = db.Song.Find(id);
            ViewBag.SongArtistID = new SelectList(db.Artist, "ArtistID", "ArtistName", song.SongArtistID);
            ViewBag.SongExtensionID = new SelectList(db.Extension, "ExtensionID", "ExtensionName", song.SongExtensionID);
            ViewBag.SongGenreID = new SelectList(db.Genre, "GenreID", "GenreName", song.SongGenreID);
            ViewBag.SongLanguageID = new SelectList(db.Language, "LanguageID", "LanguageName", song.SongLanguageID);
            VSong vSong = new VSong(song);
            return View(vSong);
        }

        //
        // POST: /VSong/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(VSong vSong)
        {
            try
            {
                var newsong = Newsong(vSong);
                db.Entry(newsong).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {

                ViewBag.SongArtistID = new SelectList(db.Artist, "ArtistID", "ArtistName");
                ViewBag.SongExtensionID = new SelectList(db.Extension, "ExtensionID", "ExtensionName");
                ViewBag.SongGenreID = new SelectList(db.Genre, "GenreID", "GenreName");
                ViewBag.SongLanguageID = new SelectList(db.Language, "LanguageID", "LanguageName");
                
                return View(vSong);
            }
        }

        //
        // GET: /VSong/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Guid id)
        {
            Song song = db.Song.Find(id);
            VSong vSong = new VSong(song);
            return View(vSong);
        }

        //
        // POST: /VSong/Delete/5

        [HttpPost]
        public ActionResult Delete(Guid id, FormCollection collection)
        {
            try
            {
                Song song = db.Song.Find(id);
                string filePath = Server.MapPath(song.SongPath);
                FileInfo file = new FileInfo(filePath);
                if (file.Exists)
                {
                    file.Delete(); //删除单个文件
                }
                db.Song.Remove(song);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                Song song = db.Song.Find(id);
                VSong vSong = new VSong(song);
                return View(vSong);
            }
        }

        public ActionResult Upload()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult Upload(HttpPostedFileBase fileData,Guid guid)
        {
            if (fileData != null)
            {
                try
                {
                    // 文件上传后的保存路径
                    string filePath = Server.MapPath("~/upload/");
                    if (!Directory.Exists(filePath))
                    {
                        Directory.CreateDirectory(filePath);
                    }
                    string fileName = Path.GetFileName(fileData.FileName);// 原始文件名称
                    string fileExtension = Path.GetExtension(fileName); // 文件扩展名
                    Extension extension = db.Extension.FirstOrDefault(e =>
                                                                      string.Compare("." + e.ExtensionName, fileExtension,
                                                                                     StringComparison
                                                                                         .InvariantCultureIgnoreCase) ==
                                                                      0);
                    //Guid guid = Guid.NewGuid();
                    string saveName = guid + fileExtension; // 保存文件名称
                    string savePath = filePath + saveName;
                    FileInfo file = new FileInfo(savePath);
                    if (file.Exists)
                    {
                        file.Delete(); //删除单个文件
                    }
                    fileData.SaveAs(savePath);

                    if (extension != null)
                    {
                        return Json(new { Success = true, FileExtension = extension.ExtensionID, Path = "~/upload/" + saveName, Guid = guid });
                    }
                    else
                    {

                        throw new Exception("后缀名不一致");
                    }
                }
                catch (Exception ex)
                {
                    return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {

                return Json(new { Success = false, Message = "请选择要上传的文件！" }, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "Admin")]
        public JsonResult LoadSongList(FormCollection collection)
        {
            Guid SongArtistID;
            Guid SongGenreID;
            Guid SongLanguageID;
            string SongName;
            int Intonation;
            int Rhythm;
            int Tone;
            int page = 1;
            int rows = 10;
            page = page <= 0 ? 1 : page;
            rows = rows <= 0 ? 10 : rows;
            int.TryParse(collection["page"], out page);
            int.TryParse(collection["rows"], out rows);
            int isSearch = 0;
            int.TryParse(collection["isSearch"], out isSearch);
            if (isSearch == 1)
            {
                int.TryParse(collection["Tone"], out Tone);
                int.TryParse(collection["Intonation"], out Intonation);
                int.TryParse(collection["Rhythm"], out Rhythm);
                SongName = string.IsNullOrEmpty(collection["SongName"]) ? string.Empty : collection["SongName"];
                SongLanguageID = string.IsNullOrEmpty(collection["SongLanguageID"]) ? Guid.Empty : new Guid(collection["SongLanguageID"]); ;

SongScreenerMvc/Views/VSong/Create.cshtml
@model SongScreenerMvc.Models.VSong
@{
    ViewBag.Title = "Create";
}
<style>
    .popupbg {
        position: fixed;
        top: 0px;
        bottom: 0px;
        min-width: 100%;
        min-height: 100%;
        background-color: black;
        display: none;
        z-index: 100;
        filter: alpha(Opacity=50);
        -moz-opacity: 0.5;
        opacity: 0.5;
        left: 0px;
    }

    .popupResult {
        position: absolute;
        width: 345px;
        border: 1px solid #cdcdcd;
        display: none;
        height: 200px;
        background: #dbf0f9;
        margin: 10% 33.5%;
        z-index: 105;
    }

    .uploadify-button {
        background-color: transparent;
        border: none;
        padding: 0;
    }

    .useBox {
        border: 1px solid #ccc;
        padding: 2px;
        font-size: 1.2em;
        color: #444;
        width: 206px;
    }

    .uploadify:hover .uploadify-button {
        background-color: transparent;
    }
</style>
<h2>添加歌曲</h2>
<link href="@Url.Content("~/Content/uploadify.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.uploadify.min.js")" type="text/javascript"></script>

<script type="text/javascript">

    function showPop() {
        $("#popupbg").fadeIn("slow");
        $("#popupResult").fadeIn("slow");
    }

    function hiddenPop() {
        $("#popupbg").fadeOut("slow");
        $('#popupResult').fadeOut("slow");
    }

    function GetPop() {
        $.ajax({
            url: "/Artist/Create",
            async: false,
            error: function () {

            },
            success: function (data) {
                showPop();
                $("#popupResult").html(data);
            }
        });
    }

    function chkCombobox(comboName) {
      var data =  $("#" + comboName).combobox('getData');
      var sval = $("#" + comboName).combobox('getValue');
        var flag = 0;
      for (var i = 0; i < data.length; i++) {
          if (data[i].value==sval) {
              flag = 1;
          }
      }
        return flag;
    }
    function realUpload() {
        if (!$("form").valid()) {
            alert("请输入歌曲名");
            return;
        }

        if ( chkCombobox("SongArtistID")<1) {
            alert("输入可用的歌手名");
            return;
        }
        if (chkCombobox("SongGenreID") < 1) {
            alert("输入可用的流派");
            return;
        }
        if (chkCombobox("SongLanguageID") < 1) {
            alert("输入可用的语言");
            return;
        }
       
        $("#dialog-confirm").show();
        $("#dialog-confirm").dialog({
            resizable: false,
            height: 220,
            modal: true,
            buttons: [{
                text: "确定",
                iconCls: 'icon-ok',
                handler: function () {

                    $("#dialog-confirm").dialog("close");
                    $('#file_upload').uploadify('upload');
                }
            }, {
                text: "取消",
                iconCls: 'icon-cancel',
                handler: function () {
                    $("#dialog-confirm").dialog("close");
                }
            }
            ]
        });


    }

    function setSlidersAndCombox() {

        SliderHelper("Intonation");
        SliderHelper("Rhythm");
        SliderHelper("Tone");
        ComboxHelper("SongArtistID");
        ComboxHelper("SongGenreID");
        ComboxHelper("SongLanguageID");
    }

    function SliderHelper(textboxName) {

        $("#" + textboxName).slider({
            min: 1,
            max: 10,
            value: 2,
            width: $("#" + textboxName).width(),
            //rule: [0, '|', 2.5, '|', 5, '|', 7.5, '|', 10],
            onSlideEnd: function (value) {
                $("#" + textboxName).val(value);
            },
            showTip: true

        });
    }

    function ComboxHelper(selectName) {
        $("#" + selectName).combobox({
            required: true,
            width: $("#" + selectName).width(),
            filter: function (q, row) {
                var opts = $(this).combobox('options');
                return row[opts.textField].indexOf(q) != -1;
            }
        });
        //$("#" + selectName).combobox("textbox").css("padding", "0");
        //$("#" + selectName).combobox("textbox").css("border", "0");;
    }

  


    $(function () {
        $('#file_upload').uploadify({
            'buttonText': '选择文件',
            'swf': '@Url.Content("~/Scripts/uploadify.swf")',
            'uploader': '/VSong/Upload?guid=' + $("#hiddenGuid").val(),
            multi: false,
            'uploadLimit': 1,
            'auto': false,
            'fileTypeDesc': '音乐文件',
            'fileTypeExts': '*.mp3; *.ogg; *.wma;*.wav;*.m4a',
            'width': 80,
            'onSelectError': function (file, errorCode, errorMsg) {
                switch (errorCode) {
                    case -100:
                        this.queueData.errorMsg = "只能选择一个文件";
                    default:
                }
            },
            'onSelect': function (file) {
                $("#uploadit").fadeIn();
            },
            'onCancel': function (file) {
                $("#uploadit").fadeOut();
            },
            'onUploadSuccess': function (file, data, response) {
                eval("data=" + data);
                //alert(data.Guid);
                $("#uploadit").fadeOut();
                $("#SongID").val(data.Guid);
                $("#SongExtensionID").val(data.FileExtension);
                $("#FliePath").val(data.Path);
                $("form").submit();

                //$("form").submit(function (e) {
                //    //alert("Submitted");
                //});
            }
        });
        setSlidersAndCombox();
        //$("#newArtist").mouseenter(function () {
        //$("#addArtist").hide();
        //    $('#addArtist').show();
        //});
    });

</script>
<div id="popupbg" class="popupbg"></div>
<div id="popupResult" class="popupResult"></div>
<div id="dialog-confirm" title="是否上传?" style="display: none">
    <p>
        将会上传音乐文件并创建歌曲记录,确定这样做吗?
    </p>
</div>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>歌曲</legend>
        <input type="hidden" id="hiddenGuid" value="@Guid.NewGuid().ToString()"/>
        @Html.HiddenFor(model => model.SongID)
        @Html.HiddenFor(model => model.SongExtensionID)
        @Html.HiddenFor(model => model.FliePath)
        <div class="editor-label">
            @Html.LabelFor(model => model.SongName)
        </div>
        <div class="editor-field" style="width: 210px">
            @Html.EditorFor(model => model.SongName)
            @Html.ValidationMessageFor(model => model.SongName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Language)
        </div>
        <div class="editor-field" style="width: 210px">
            @Html.DropDownList("SongLanguageID", (IEnumerable<SelectListItem>)ViewBag.SongLanguageID, new { @class = "useBox" })
            @Html.ValidationMessageFor(model => model.SongLanguageID)
        </div>

        <div class="editor-label" >
            @Html.LabelFor(model => model.Artist)
        </div>
        <div class="editor-field" style="width: 210px">
            @Html.DropDownList("SongArtistID", (IEnumerable<SelectListItem>)ViewBag.SongArtistID, new { @class = "useBox" })
            @Html.ValidationMessageFor(model => model.SongArtistID)
               
            @*<span id ="newArtist">找不到歌手?</span>*@
            @*<input type="button" id="addArtist" class="uploadify-button" onclick="GetPop()" style="width: 80px; height: 20px;/*display: none*/" value="添加歌手" />*@
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Genre)
        </div>
        <div class="editor-field" style="width: 210px">
            @Html.DropDownList("SongGenreID", (IEnumerable<SelectListItem>)ViewBag.SongGenreID, new { @class = "useBox" })
            @Html.ValidationMessageFor(model => model.SongGenreID)
        </div>

        <div class="editor-label" >
            @Html.LabelFor(model => model.Intonation)
        </div>
        <div class="editor-field" style="margin-top: 20px; margin-bottom: 20px;width: 210px">

            @Html.EditorFor(model => model.Intonation)
            @Html.ValidationMessageFor(model => model.Intonation)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tone)
        </div>
        <div class="editor-field" style="margin-top: 20px; margin-bottom: 20px;width: 210px">
            @Html.EditorFor(model => model.Tone)
            @Html.ValidationMessageFor(model => model.Tone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rhythm)
        </div>
        <div class="editor-field" style="margin-top: 20px; margin-bottom: 20px;width: 210px">
            @Html.EditorFor(model => model.Rhythm)
            @Html.ValidationMessageFor(model => model.Rhythm)
        </div>
        <div class="editor-label">
            <p>上传</p>
        </div>
        <div class="editor-field">
            <input type="file" id="file_upload" name="file_upload" />
            <input type="button" id="uploadit" class="uploadify-button" style="display: none; width: 90px; height: 30px" value="上传并创建歌曲" onclick="realUpload();" />

        </div>
        <p>
            @*            <input type="submit" value="选择文件" />*@
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("返回歌曲列表", "Index")
</div>

SongScreenerMvc/Views/VSong/Delete.cshtml
@model SongScreenerMvc.Models.VSong
@{
    ViewBag.Title = "Delete";
}


<h2>确定删除歌曲吗?</h2>
<fieldset>
    <legend>歌曲</legend>

    @*<div class="display-label">SongID</div>*@
    <div class="display-field">
        @Html.HiddenFor(model => model.SongID)
    </div>

    <div class="display-label" style="font-weight: bold">
        @Html.LabelFor(model => model.SongName)
    </div>
    <div class="display-field" style="border-bottom: 1px #5C87B2 solid;width: 100px">
        @Html.DisplayFor(model => model.SongName)
    </div>

    <div class="display-label" style="font-weight: bold">
        @Html.LabelFor(model => model.Intonation)
    </div>
    <div class="display-field" style="border-bottom: 1px #5C87B2 solid;width: 100px">
        @Html.DisplayFor(model => model.Intonation)
    </div>

    <div class="display-label" style="font-weight: bold">
        @Html.LabelFor(model => model.Tone)
    </div>
    <div class="display-field" style="border-bottom: 1px #5C87B2 solid;width: 100px">
        @Html.DisplayFor(model => model.Tone)
    </div>

    <div class="display-label" style="font-weight: bold">
        @Html.LabelFor(model => model.Rhythm)
    </div>
    <div class="display-field" style="border-bottom: 1px #5C87B2 solid;width: 100px">
        @Html.DisplayFor(model => model.Rhythm)
    </div>

    

    <div class="display-label" style="font-weight: bold">
        @Html.LabelFor(model => model.Artist)
    </div>
    <div class="display-field" style="border-bottom: 1px #5C87B2 solid;width: 100px">
        @Html.DisplayFor(model => model.Artist.ArtistName)
    </div>

    <div class="display-label" style="font-weight: bold">
        @Html.LabelFor(model => model.Language)
    </div>
    <div class="display-field" style="border-bottom: 1px #5C87B2 solid;width: 100px">
        @Html.DisplayFor(model => model.Language.LanguageName)
    </div>

    <div class="display-label" style="font-weight: bold">
        @Html.LabelFor(model => model.Genre)
    </div>
    <div class="display-field" style="border-bottom: 1px #5C87B2 solid;width: 100px">
        @Html.DisplayFor(model => model.Genre.GenreName)
    </div>
    <div class="display-label" style="font-weight: bold">
        @Html.LabelFor(model => model.FliePath)
    </div>
    <div class="display-field"  style="border-bottom: 1px #5C87B2 solid;width: 300px">
        @Html.DisplayFor(model => model.FliePath)
    </div>
    @*<div class="display-label">SongExtensionID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SongExtensionID)
    </div>*@
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="删除" />
        |
        @Html.ActionLink("返回歌曲列表", "Index")
    </p>
}

SongScreenerMvc/Views/VSong/Details.cshtml
@model SongScreenerMvc.Models.VSong

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>VSong</legend>

    <div class="display-label">SongID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SongID)
    </div>

    <div class="display-label">SongName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SongName)
    </div>

    <div class="display-label">Intonation</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Intonation)
    </div>

    <div class="display-label">Tone</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tone)
    </div>

    <div class="display-label">Rhythm</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rhythm)
    </div>

    <div class="display-label">FliePath</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FliePath)
    </div>

    <div class="display-label">SongArtistID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SongArtistID)
    </div>

    <div class="display-label">SongLanguageID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SongLanguageID)
    </div>

    <div class="display-label">SongGenreID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SongGenreID)
    </div>

    <div class="display-label">SongExtensionID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SongExtensionID)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SongScreenerMvc/Views/VSong/Upload.cshtml
@model SongScreenerMvc.Models.VSong

@{
    ViewBag.Title = "上传音乐文件";
    Layout = null;
}

<h2>@ViewBag.Title</h2>
<script type="text/javascript">
function fileSelected() {
        var file = document.getElementById('fileToUpload').files[0];
        if (file) {
            var fileSize = 0;
            if (file.size > 1024 * 1024)
                fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
            else
                fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';

            document.getElementById('fileName').innerHTML = 'Name: ' + file.name;
            document.getElementById('fileSize').innerHTML = 'Size: ' + fileSize;
            document.getElementById('fileType').innerHTML = 'Type: ' + file.type;
        }
    }

    function uploadFile() {
        var fd = new window.FormData();
        fd.append("fileToUpload", document.getElementById('fileToUpload').files[0]);
        var xhr = new XMLHttpRequest();
        xhr.upload.addEventListener("progress", uploadProgress, false);
        xhr.addEventListener("load", uploadComplete, false);
        xhr.addEventListener("error", uploadFailed, false);
        xhr.addEventListener("abort", uploadCanceled, false);
        xhr.open("POST", "Upload");
        xhr.send(fd);
    }

    function uploadProgress(evt) {
        if (evt.lengthComputable) {
            var percentComplete = Math.round(evt.loaded * 100 / evt.total);
            document.getElementById('progressNumber').innerHTML = percentComplete.toString() + '%';
        }
        else {
            document.getElementById('progressNumber').innerHTML = 'unable to compute';
        }
    }

    function uploadComplete(evt) {
        /* This event is raised when the server send back a response */
        //alert(evt.target.responseText);
    }

    function uploadFailed(evt) {
        alert("There was an error attempting to upload the file.");
    }

    function uploadCanceled(evt) {
        alert("The upload has been canceled by the user or the browser dropped the connection.");
}
</script>

@using (Html.BeginForm("Upload", "VSong", FormMethod.Post, new { enctype = "multipart/form-data" , id="form1"}))
{    
    

    <div class="row">
            <label for="file">
                上传文件:</label>
            <input type="file" name="fileToUpload" id="fileToUpload"   onchange="fileSelected();" />
        </div>
        
        <div id="fileName">
        </div>
        <div id="fileSize">
        </div>
        <div id="fileType">
        </div> 
        <div class="row">
            <input type="button" onclick="uploadFile()" value="上传" />
            <input type="button" onclick="hiddenPop();" value="关闭" />

        </div>
        <div id="progressNumber">
        </div>
}